### ISSUE TITLE
Offline on Discord

### ISSUE THREAD

**Issue by Vicct1** [MizaGBF/MizaBOT#10]
Hello

Trying to make your bot for a server of my own and after following the instructions in the setup page i got it running on Heroku (python worker3 bot worker online and working and the deploy commands for both cloning the repository localy on my machine or update on Heroku works too) but it still won't go online in Discord on neither the debug server or the server i intend to use it, copied the bot token and the servers ID/channels in config.json already.
Can you help me in understanding what i might do wrong please?

**Comment by Vicct1** [comment]
nvm, got it work. had error in my config and save.json.
Adding a "version": 1 in save.json on line 2 top of "newserver": {  did the work it seems

**Comment by MizaGBF** [comment]
Ah good point, I recently changed the save file format.  
I'll update the example.  
Thanks for pointing it out.

**Comment by MizaGBF** [comment]
After looking more closely into it, it should have been `"version": 0` but the checks I put in place would had made sure the save file is correct, so don't worry about it.
