### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by Lathos05** [MizaGBF/MizaBOT#16]
Hi, I have some question regarding the bot. 
My friend show this to me and I tried to copy it but 
I'm having some trouble setting it up.

![AUTH](https://user-images.githubusercontent.com/86822904/167265200-36ed28b1-8a26-4876-8818-a424fe6516b9.png)

**Comment by MizaGBF** [comment]
Your config.json file isn't setup/filled properly and the bot isn't finding the tokens needed to access your google drive
