### ISSUE TITLE
Can't create credential.json 

### ISSUE THREAD

**Issue by atliv** [MizaGBF/MizaBOT#17]
hi miza, i tried to run your bot in my own server but it doesn't generate credentials.json in my locals environment.

i have been following your guide but this error is pop out 
![image](https://user-images.githubusercontent.com/10157718/170824763-9fbd6ec7-cc7c-4537-821c-4862695b4e8a.png)

and here's my settings.yaml
![image](https://user-images.githubusercontent.com/10157718/170824803-3f94643e-34ab-4ab2-a180-344c4c23ce6c.png)

**Comment by MizaGBF** [comment]
There is an error in generate_gdrive_credentials.py (probably because I never used this version of the script): line 4 should be gauth.credentials and not self.gauth.credentials.  
It should fix the error.  
If it doesn't, it will ask you to put client_secrets.json in the same folder.

**Comment by atliv** [comment]
after i follow the steps from this [#1](url) issue, it finally worked. btw thanks for fast reply.
